-- Usuń tabelę jeśli istnieje (bezpieczne dla restartów)
DROP TABLE IF EXISTS customer;

-- Utwórz tabelę customer
CREATE TABLE IF NOT EXISTS customer (
    id BIGSERIAL PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL
);

-- Wstaw 300 rekordów Customer
INSERT INTO customer (firstname, lastname) VALUES
('Jan', 'Kowalski'), ('Anna', 'Nowak'), ('Piotr', 'Wiśniewski'), ('Maria', 'Lewandowska'), ('Krzysztof', 'Jankowski'),
('Katarzyna', 'Wojciechowska'), ('Michał', 'Kamiński'), ('Alicja', 'Mazur'), ('Tomasz', 'Kwiatkowski'), ('Ewa', 'Krawczyk'),
('Paweł', 'Kaczmarek'), ('Monika', 'Piotrowska'), ('Marek', 'Wiśniewska'), ('Agnieszka', 'Zielińska'), ('Grzegorz', 'Szymański'),
('Joanna', 'Wójcik'), ('Adam', 'Kozłowski'), ('Karolina', 'Grabowska'), ('Łukasz', 'Pawłowski'), ('Zofia', 'Falińska'),
('Mateusz', 'Michalski'), ('Julia', 'Nowińska'), ('Sebastian', 'Rutkowski'), ('Nina', 'Baranowska'), ('Dominik', 'Dąbrowski'),
('Wiktoria', 'Olszewska'), ('Jakub', 'Sikora'), ('Oliwia', 'Waszczykowska'), ('Patryk', 'Adamczyk'), ('Zuzanna', 'Szewczyk'),
('Kamil', 'Stępień'), ('Amelia', 'Piątek'), ('Dawid', 'Cieślak'), ('Lena', 'Woźniak'), ('Bartosz', 'Krupa'),
('Maja', 'Barczyk'), ('Filip', 'Jasiński'), ('Hanna', 'Zając'), ('Alan', 'Wroński'), ('Laura', 'Niedźwiedzka'),
('Nikodem', 'Sokołowski'), ('Gabriela', 'Chmiel'), ('Igor', 'Puchalski'), ('Nadia', 'Laskowski'), ('Krystian', 'Białas'),
('Sara', 'Wilk'), ('Miłosz', 'Szulc'), ('Blanka', 'Gajewska'), ('Kacper', 'Makowski'), ('Iga', 'Sadowska'),
('Szymon', 'Okręglak'), ('Marta', 'Klich'), ('Bruno', 'Zalewski'), ('Kornelia', 'Urban'), ('Radosław', 'Kowalczyk'),
('Kinga', 'Pasternak'), ('Oskar', 'Sławiński'), ('Milena', 'Górska'), ('Emil', 'Lemański'), ('Zofia', 'Jurkiewicz'),
('Leon', 'Wójtowicz'), ('Aleksandra', 'Brzezińska'), ('Ignacy', 'Krawiec'), ('Weronika', 'Szczepańska'), ('Teodor', 'Kalisz'),
('Natalia', 'Pietrzak'), ('Franciszek', 'Warchoł'), ('Melania', 'Kostrzewa'), ('Borys', 'Wilk'), ('Rozalia', 'Mazurek'),
('Mikołaj', 'Raczyński'), ('Inga', 'Domański'), ('Jeremi', 'Łukasiewicz'), ('Antonia', 'Kiełbasa'), ('Wojciech', 'Sarnowski'),
('Kalina', 'Trzcińska'), ('Marceli', 'Garczyński'), ('Roksana', 'Wesołowska'), ('Cezary', 'Kopczyński'), ('Jagoda', 'Płatek'),
('Tymoteusz', 'Kiełtyka'), ('Lidia', 'Brodziak'), ('Konrad', 'Żurawski'), ('Helena', 'Kochanowska'), ('Maksymilian', 'Sroka'),
('Antonina', 'Drożdż'), ('Gabriel', 'Kiełbowicz'), ('Urszula', 'Witas'), ('Noe', 'Strzelczyk'), ('Izabela', 'Garczyńska'),
('Błażej', 'Woliński'), ('Stefania', 'Kiełbik'), ('Klaudiusz', 'Pazdro'), ('Apolonia', 'Żywczak'), ('Ryszard', 'Kiełtyka'),
('Dorota', 'Warchoł'), ('Sławomir', 'Kostecki'), ('Beata', 'Sarnowska'), ('Dariusz', 'Trzciński'), ('Elżbieta', 'Garczyńska'),
('Artur', 'Malinowski'), ('Barbara', 'Pawlak'), ('Bogdan', 'Sadowski'), ('Cecylia', 'Górski'), ('Czesław', 'Witkowski'),
('Danuta', 'Król'), ('Edward', 'Pawlik'), ('Eugenia', 'Wróbel'), ('Feliks', 'Walczak'), ('Genowefa', 'Rutkowska'),
('Halina', 'Jabłońska'), ('Henryk', 'Majewski'), ('Irena', 'Olszewski'), ('Janina', 'Stępień'), ('Jerzy', 'Jaworski'),
('Józef', 'Malinowska'), ('Kazimierz', 'Pawlak'), ('Krystyna', 'Dudek'), ('Lucyna', 'Nowakowska'), ('Ludwik', 'Zawadzki'),
('Marianna', 'Czarnecki'), ('Mirosław', 'Kowalczyk'), ('Renata', 'Wojciechowski'), ('Roman', 'Kwiatkowska'), ('Stanisław', 'Krawczyk'),
('Teresa', 'Kamiński'), ('Urszula', 'Piotrowska'), ('Władysław', 'Grabowski'), ('Zbigniew', 'Nowakowski'), ('Zofia', 'Zielińska'),
('Andrzej', 'Pawłowski'), ('Bronisława', 'Szymańska'), ('Czesława', 'Wójcik'), ('Damian', 'Kozłowska'), ('Eugeniusz', 'Mazur'),
('Franciszka', 'Jankowska'), ('Genowefa', 'Wojciechowska'), ('Grażyna', 'Kowalska'), ('Henryka', 'Dąbrowska'), ('Ireneusz', 'Zając'),
('Jadwiga', 'Kamińska'), ('Jan', 'Wieczorek'), ('Janusz', 'Kołodziej'), ('Jolanta', 'Szewczyk'), ('Józefa', 'Król'),
('Kazimiera', 'Michalak'), ('Krzysztof', 'Wróbel'), ('Lech', 'Jaworski'), ('Ludmiła', 'Walczak'), ('Łucja', 'Stępień'),
('Małgorzata', 'Witkowski'), ('Mariusz', 'Górski'), ('Mieczysław', 'Rutkowski'), ('Mirosława', 'Duda'), ('Natalia', 'Kowalczyk'),
('Olga', 'Lewandowski'), ('Piotr', 'Kucharski'), ('Paulina', 'Zawadzki'), ('Rafał', 'Czarnecki'), ('Regina', 'Sobczak'),
('Robert', 'Sikora'), ('Roman', 'Borowski'), ('Ryszard', 'Krajewski'), ('Stanisława', 'Maciejewski'), ('Stefan', 'Błaszczyk'),
('Sylwester', 'Sawicki'), ('Tadeusz', 'Chmielewski'), ('Urszula', 'Baran'), ('Wanda', 'Tomaszewski'), ('Wiktor', 'Kozioł'),
('Władysława', 'Szczepański'), ('Wojciech', 'Krawczyk'), ('Zdzisław', 'Urbański'), ('Zofia', 'Laskowski'), ('Alina', 'Włodarczyk'),
('Aleksander', 'Baranowski'), ('Alfred', 'Czerwiński'), ('Amelia', 'Ostrowski'), ('Anatol', 'Przybylski'), ('Angelika', 'Przybylska'),
('Anita', 'Malinowska'), ('Antoni', 'Kowalski'), ('Antonina', 'Nowak'), ('Apolonia', 'Cieślak'), ('Arnold', 'Kalinowski'),
('Augustyn', 'Marciniak'), ('Aurelia', 'Woźniak'), ('Bazyli', 'Kucharski'), ('Benedykt', 'Szulc'), ('Beniamin', 'Tomczak'),
('Bernadeta', 'Dąbrowski'), ('Bernard', 'Krajewski'), ('Bogna', 'Brzozowski'), ('Bogusław', 'Mazurkiewicz'), ('Bogumiła', 'Kaczmarek'),
('Bolesław', 'Krupa'), ('Borys', 'Jasiński'), ('Bożena', 'Zając'), ('Brygida', 'Wójcik'), ('Cecylia', 'Sikora'),
('Celestyn', 'Kowalczyk'), ('Celina', 'Nowak'), ('Cyprian', 'Pawłowski'), ('Czesław', 'Michalski'), ('Dagmara', 'Rutkowski'),
('Daniela', 'Baranowska'), ('Danuta', 'Dąbrowski'), ('Daria', 'Olszewska'), ('Dawid', 'Sikora'), ('Diana', 'Waszczykowska'),
('Dionizja', 'Adamczyk'), ('Dominika', 'Szewczyk'), ('Donata', 'Stępień'), ('Dorian', 'Piątek'), ('Doris', 'Cieślak'),
('Dorota', 'Woźniak'), ('Edmund', 'Krupa'), ('Edyta', 'Barczyk'), ('Eleonora', 'Jasiński'), ('Eliasz', 'Zając'),
('Eliza', 'Wroński'), ('Emanuel', 'Niedźwiedzka'), ('Emilia', 'Sokołowski'), ('Emil', 'Chmiel'), ('Ernest', 'Puchalski'),
('Erwin', 'Laskowski'), ('Estera', 'Białas'), ('Eugeniusz', 'Wilk'), ('Eufemia', 'Szulc'), ('Eustachy', 'Gajewska'),
('Ewa', 'Makowski'), ('Ewelina', 'Sadowska'), ('Fabian', 'Okręglak'), ('Fabiana', 'Klich'), ('Felicja', 'Zalewski'),
('Felicjan', 'Urban'), ('Feliks', 'Kowalczyk'), ('Ferdynand', 'Pasternak'), ('Filip', 'Sławiński'), ('Florian', 'Górska'),
('Franciszek', 'Lemański'), ('Fryderyk', 'Jurkiewicz'), ('Gabriel', 'Wójtowicz'), ('Gabriela', 'Brzezińska'), ('Gaweł', 'Krawiec'),
('Genowefa', 'Szczepańska'), ('Gerard', 'Kalisz'), ('Gertruda', 'Pietrzak'), ('Gerwazy', 'Warchoł'), ('Gniewomir', 'Kostrzewa'),
('Godfryd', 'Wilk'), ('Gracja', 'Mazurek'), ('Grzegorz', 'Raczyński'), ('Gustaw', 'Domański'), ('Gwido', 'Łukasiewicz'),
('Halina', 'Kiełbasa'), ('Hanna', 'Sarnowski'), ('Helena', 'Trzcińska'), ('Henryk', 'Garczyński'), ('Herbert', 'Wesołowska'),
('Hilary', 'Kopczyński'), ('Hipolit', 'Płatek'), ('Honorata', 'Kiełtyka'), ('Hubert', 'Brodziak'), ('Ida', 'Żurawski'),
('Idalia', 'Kochanowska'), ('Ignacy', 'Sroka'), ('Igor', 'Drożdż'), ('Ilona', 'Kiełbowicz'), ('Ildefons', 'Witas');
